package com.example.psk_1.mybatis.dao;

import com.example.psk_1.mybatis.model.Teacher;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface TeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEACHER
     *
     * @mbg.generated Mon Apr 08 20:37:25 EEST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEACHER
     *
     * @mbg.generated Mon Apr 08 20:37:25 EEST 2024
     */
    int insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEACHER
     *
     * @mbg.generated Mon Apr 08 20:37:25 EEST 2024
     */
    Teacher selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEACHER
     *
     * @mbg.generated Mon Apr 08 20:37:25 EEST 2024
     */
    List<Teacher> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEACHER
     *
     * @mbg.generated Mon Apr 08 20:37:25 EEST 2024
     */
    int updateByPrimaryKey(Teacher record);
}